pipeline {
    agent any
	
	tools {
	   jdk 'JAVA_HOME'
	    gradle 'GRADLE_HOME'
		dockerTool 'CustomeDocker'
		 
	} 
	   
	environment {
	    DOCKER    = "${dockerTool1}/bin"
	    JAVA_HOME = "${jdk}"
		REPO = ""
		
		
	}
    
    stages {
        stage('Clone'){
             steps {
			   dir('pascaldev-configuration-repository'){
					
					checkout([$class: 'GitSCM', branches: [[name: '*/master']],
					doGenerateSubmoduleConfigurations: false,
					extensions: [
					[$class: 'CloneOption', depth: 1, noTags: true, reference: '', shallow: true, timeout: 120]],
					submoduleCfg: [],userRemoteConfigs: [[credentialsId: 'a6280c9b-a503-48e3-9c38-face160c8be6', url:
					 'http://saas1402fu.saas-secure.com/git/pascaldev-configuration-repository.git']]])
				 }
				 sh """ 
				   echo " ${env.WORKSPACE}"
				 """
				//checkout([$class: 'GitSCM', branches: [[name: '*/master']],
                //doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CloneOption', depth: 1, noTags: true, reference: '', shallow: true, timeout: 120]], 
				//submoduleCfg: [],userRemoteConfigs: [[credentialsId: 'a6280c9b-a503-48e3-9c38-face160c8be6', url:
                // 'http://saas1402fu.saas-secure.com/git/pascaldev-configuration-service.git']]])
				 
				 
			 }
        }
        stage('Build') {
            steps {	
                sh 'chmod +x gradlew'                
                gradlew('clean', 'assemble')
				sh 'ls build/libs/'	
            	
            }
        }
		 stage('Unit Tests') {
					steps {
					  script{
						 try {
							 dir('pascaldev-configuration-service'){
								
							  sh 'chmod +x gradle' 
							  sh './gradlew test '
							 
						  }
						}catch(exc) {
						 def summary = junit  skipPublishingChecks: true, testResults: '**/TEST-*.xml' 
							   sh "echo ${summary.totalCount}"
							   sh " echo ${summary.failCount}"
							   sh "echo ${summary.skipCount} " 
							   sh "echo ${summary.passCount} " 
							   def percentage = summary.passCount*100/summary.totalCount
							   sh "echo ${percentage}"
					     if ( ${percentage} < 98){
						    currentBuild.result = 'FAILURE'
					     }
						 currentBuild.result = 'SUCCESS'
						}
					 }
					}
				} 
        //stage('SonarQube analysis') {
           // steps {	
            	//withSonarQubeEnv('SonarQube') {
                //    gradlew('sonarqube')
                //}
           // }
        //}       
        
                 
        //stage('Integration Tests') {
			//steps {
			//	gradlew('integrationTest -i')
			//}
			//post {
			//	always {
				//	junit '**/build/test-results/integrationTest/TEST-*.xml'
				//}
			//}
		//}
		//stage('Docker build image') {
          //steps {
		 
            //  dockerCmd "build -t pascaldev-configuration-service-docker-image:${env.BUILD_NUMBER} ."
         // }
        // }
		
	   // stage('Docker tag image latest') {
			 // steps {
			// dockerCmd "tag pascaldev-configuration-service-docker-image:${env.BUILD_NUMBER}  pascaldev-configuration-service-docker-image:latest "
				   
			 //  }
		//}
		//stage('Docker image ') {
			//  steps {
			 //  dockerCmd "tag pascaldev-configuration-service-docker-image localhost:5000/pascaldev-configuration-service-docker-image "
				   
		  // }
        //}
	   // stage('Docker push image latest') {
          // steps {
          //   dockerCmd "push localhost:5000/pascaldev-configuration-kubernetes-service-docker-image"
               
         // }
         // }
	  //  stage('Deploy app'){
			//steps{
					//script{
						// kubernetesDeploy(configs:"deployment-configuration-service.yml", kubeconfigId:"kubeconfiguration")
									
					//}
			//}
		//}
		
    }
    post {
				always {
				 dir('/var/lib/jenkins/workspace/pascaldev-configuration-service/pascaldev-configuration-service/build/test-results/test/'){
					 junit  skipPublishingChecks: true, testResults: '**/TEST-*.xml'
					  sh 'ls'
				 }		 
			   }
			 failure {
				mail to: 'pascalyakouyami@gmail.com', subject: 'Pascaldev Configuration microservice build failed', body: 'Pascaldev Configuration microservice build failed.\nPlease fix!'
			}
		}
}

def gradlew(String... args) {
    sh "./gradlew ${args.join(' ')} -s"
}

def dockerCmd(args) {
    sh "echo ${tool 'CustomeDocker'}"
    sh "echo ${env.DOCKER_HOST}"
    sh "${tool 'CustomeDocker'}/bin/docker ${args}"
}